name: Home Assistant MCP HTTP Server
version: "1.0.10"
slug: homeassistant_mcp_http
description: HTTP MCP server with OAuth for Claude iOS/web access
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ingress: false
panel_icon: mdi:robot
homeassistant_api: true
ports:
  3000/tcp: 3000
options:
  oauth_client_url: ""
schema:
  oauth_client_url: str
