name: "MCP Server for Home Assistant"
description: "Model Context Protocol server with full API and root-level access"
version: "0.3.3"
slug: "homeassistant-mcp-server"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - backup:rw
  - share:rw
  - media:rw
host_network: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
apparmor: false
options:
  transport: "stdio"
  port: 3000
  oauth_client_url: ""
schema:
  transport: list(stdio|http)
  port: port
  oauth_client_url: str?
