name: "MCP Server for Home Assistant"
description: "Model Context Protocol server with layered architecture (132 tools)"
version: "2.0.1"
slug: "ha-mcp-server-v2"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - config:rw
  - ssl:rw
  - addons:rw
  - backup:rw
  - share:rw
  - media:rw
host_network: true
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
apparmor: false
options:
  transport: "stdio"
  port: 3000
  oauth_client_url: ""
schema:
  transport: list(stdio|http)
  port: port
  oauth_client_url: str?
