name: Home Assistant MCP Server
version: "0.1.3"
slug: homeassistant_mcp
description: MCP server for Claude integration with Home Assistant
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
ports: {}
ports_description: {}
homeassistant_api: true
hassio_api: true
hassio_role: manager
auth_api: true
ingress: false
panel_icon: mdi:robot
options:
  log_level: info
schema:
  log_level: list(debug|info|warning|error)
